# Check out https://docs.codemagic.io/getting-started/building-a-native-ios-app/ for more information
# Please review and update values in curly braces

workflows:
    ios-app:
        name: iOS App
        environment:
            xcode: latest
            cocoapods: default
        scripts:
            - flutter build ios --debug --no-codesign
            - xcode-project use-profiles
            - xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        artifacts:
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM