# Check out https://docs.codemagic.io/getting-started/building-a-native-ios-app/ for more information
# Please review and update values in curly braces

workflows:
    ios-app:
        name: iOS App
        environment:
            vars:
                XCODE_WORKSPACE: "Runner"
                XCODE_SCHEME: "Runner"
            xcode: latest
            cocoapods: default
        scripts:
            - flutter build ios --debug --no-codesign
            # - xcode-project build-ipa --verbose --workspace ios/Runner.xcworkspace --scheme Runner 
            - xcodebuild build -workspace "$XCODE_WORKSPACE.xcworkspace" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
            - xcode-project build-ipa --workspace "Runner.xcworkspace" --scheme "Runner"
        artifacts:
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM